# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma_mc <- function(x, mean, sigma, logd = FALSE, cores = 1L) {
    .Call(`_pgR_dmvnrm_arma_mc`, x, mean, sigma, logd, cores)
}

rcpp_pgdraw <- function(b, c, cores = 1L) {
    .Call(`_pgR_rcpp_pgdraw`, b, c, cores)
}

#' A function for sampling from conditional multivariate normal distributions with mean A^{-1}b and covariance matrix A^{-1}.
#'
#' @param \code{A} A \eqn{d \times d} \code{matrix} for the Gaussian full conditional distribution precision matrix.
#' @param \code{b} A \eqn{d} \code{vector} for the Gaussian full conditional distribution mean.
#' 
#' @export
rmvn_arma <- function(A, b) {
    .Call(`_pgR_rmvn_arma`, A, b)
}

#' A function for sampling from conditional multivariate normal distributions with mean A^{-1}b and covariance matrix A^{-1}.
#'
#' @param \code{A} A scalar for the Gaussian full conditional distribution precision.
#' @param \code{b} A \eqn{d} \code{vector} for the Gaussian full conditional distribution mean.
#' 
#' @export
rmvn_arma_scalar <- function(a, b) {
    .Call(`_pgR_rmvn_arma_scalar`, a, b)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_pgR_RcppExport_registerCCallable', PACKAGE = 'pgR')
})
